server:
  port:  9001
spring:
    application:
      name: USER-SERVICE
    datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: root
      url: jdbc:mysql://localhost:3306/player_auction_ultimate?createDataBaseIfNotExist=true
      username: root
    jpa:
      hibernate:
        ddl-auto: update
      properties: 
        hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
      show-sql: true
    eureka: 
      client:
        registry-with-eureka: true
        fetch-registry: true
        service-url:
         defaultZone: http://localhost:8761/eureka/
        instance:
         hostname: localhost